version: "3.9"
services:
  postgres:
    image: postgres:14
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: dbt
      POSTGRES_PASSWORD: dbt
      POSTGRES_DB: dbt_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "niko", "-d", "dbt_database"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdata: